CUDA_VISIBLE_DEVICES=0 python run_qa.py \
  --model_name_or_path klue/bert-base \
  --train_file /raid/chrisjihee/proj/DeepKNLP-25/data/korquad/train.jsonl \
  --validation_file /raid/chrisjihee/proj/DeepKNLP-25/data/korquad/validation.jsonl \
  --do_train \
  --do_eval \
  --num_train_epochs 2 \
  --per_device_train_batch_size 12 \
  --learning_rate 3e-5 \
  --max_seq_length 512 \
  --doc_stride 128 \
  --output_dir ./output \
  --overwrite_output_dir
