CUDA_VISIBLE_DEVICES=0 python task3-qa/train_qa.py \
  --train_file data/korquad/train.json \
  --validation_file data/korquad/validation.json \
  --model_name_or_path jinmang2/kpfbert \
  --do_train \
  --do_eval \
  --per_device_train_batch_size 12 \
  --max_seq_length 512 \
  --doc_stride 128 \
  --num_train_epochs 3 \
  --learning_rate 3e-5 \
  --output_dir output/korquad/train=KPF-BERT=$(hostname) \
  --overwrite_output_dir
